[config]
default_to_workspace = false
min_version = "0.37.23"

[env]
#CARGO_MAKE_CLIPPY_ARGS = "-- --deny=warnings"
#CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

# workflow
[tasks.lint]
dependencies = ["format", "clippy"]

[tasks.test]
dependencies = ["check","clean"]
command = "cargo"
args = ["test"]

[tasks.docs]
dependencies = ["build"]
command = "cargo"
args = [
    "doc",
    "--open"
]

[tasks.test-cov]
dependencies = ["check","clean"]
command = "cargo"
args = ["tarpaulin","--out","xml"]

# for ebou
[tasks.tailwind]
command = "npx"
args = ["tailwindcss","-i","input.css","-o","assets/tailwind.css","--watch"]
[tasks.dev]
command = "dx"
args = ["serve","--port","3000","--hot-reload"]
