[package]
name = "hackernews"
version = { workspace = true }
authors = ["sicheng1806 <sicheng1806@outlook.com>"]
edition = "2021"
description = "the hackernews example app"

[dependencies]
async-recursion = { workspace=true }
chrono = { workspace=true, features = ["serde"] }
dioxus = { workspace=true, features = ["desktop"] }
futures = { workspace=true }
reqwest = { workspace=true, features = ["json"] }
serde = { workspace=true, features = ["derive"] }
serde_json = { workspace=true }
