# This workflow will install Rust dependencies, run tests and lint with a single version of Rust
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: main

on:
    push:
        branches:
            - main
            - develop
        tags:
            - "*"

    pull_request:
        branches:
            - main
            - develop

jobs:
    Test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Ubuntu dependencies
              uses: ConorMacBride/install-package@v1
              with:
                apt: libgtk-3-dev
            - name: Config Cargo
              uses: dtolnay/rust-toolchain@stable
            - name: Allow rust cache
              uses: Swatinem/rust-cache@v2
              with:
                cache-all-crates: "true"
                cache-on-failure: "true"
            - name: Config cargo-make
              uses: davidB/rust-cargo-make@v1
            - name: Run Lint
              run: cargo make lint
            - name: Run Test
              run: cargo make test
